CREATE DATABASE IF NOT EXISTS zad3;

USE zad3;

CREATE TABLE IF NOT EXISTS products (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(256) NOT NULL,
image VARCHAR(256) NOT NULL,
price FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(256) NOT NULL UNIQUE,
name VARCHAR(256) NOT NULL,
street VARCHAR(256) NOT NULL,
number VARCHAR(64) NOT NULL,
city VARCHAR(256) NOT NULL,
postal VARCHAR(256) NOT NULL
);
		
CREATE TABLE IF NOT EXISTS orders (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
customer_id INT NOT NULL,
done TINYINT(1) NOT NULL,
FOREIGN KEY (customer_id)
REFERENCES customers(id)
ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS order_product (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
product_id INT NOT NULL,
order_id INT NOT NULL,
count INT NOT NULL DEFAULT 1,
FOREIGN KEY (product_id)
REFERENCES products(id)
ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY (order_id)
REFERENCES orders(id)
ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ads (
id INT PRIMARY KEY,
link TEXT NOT NULL,
image TEXT NOT NULL,
counter INT NOT NULL DEFAULT 0
);

INSERT INTO products (id, name, image, price) VALUES 
(1, 'klavir', 'klavir.jpg', 450),
(2, 'husle', 'husle.jpg', 320),
(3, 'flauta', 'flauta.jpg', 90)
ON DUPLICATE KEY UPDATE id=id
;